In [91]:
# import pdfplumber
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords 
from string import punctuation
from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer
from nltk.probability import FreqDist
from heapq import nlargest
from collections import defaultdict
import pandas as pd 
from nltk.collocations import *
# nltk.download('punkt')
# nltk.download('stopwords')
# nltk.download('wordnet')

In [92]:
# Import CV
f=open('textfile.txt','r', errors = 'ignore')
text=f.read()

In [93]:
def nlp(x):
    word_sent = word_tokenize(x.lower().replace("\n",""))
    _stopwords = set(stopwords.words('english') + list(punctuation)+list("●")+list('–')+list('’'))
    word_sent=[word for word in word_sent if word not in _stopwords]
    lemmatizer = WordNetLemmatizer()
    NLP_Processed_CV = [lemmatizer.lemmatize(word) for word in word_tokenize(" ".join(word_sent))]
#     return " ".join(NLP_Processed_CV)
    return NLP_Processed_CV

In [94]:
def get_key_word(x):
    finder = BigramCollocationFinder.from_words(x)
    lst = []
    Key_word_from_CV = []
    for i in sorted(finder.ngram_fd.items()):
    # if a double word appears more than once, then print it out.
        if i[1] > 1:
            print(i)
            lst.append(i[0])
        else:
            pass

    # print("************************")
    for j in lst:
    #     print(" ".join(j))
        Key_word_from_CV.append(" ".join(j))
    return Key_word_from_CV

In [95]:
NLP_Processed_CV = nlp(text)
# NLP_Processed_CV=' '.join(NLP_Processed_CV)
NLP_Processed_CV

['unnamed',
 '0',
 'name',
 'email',
 'mobile_number',
 'skill',
 'degree',
 'no_of_pages',
 'file_path',
 'pdf_to_base640',
 'le',
 'thanh',
 'attentionocr',
 'gmail.com,096-997-3012',
 '``',
 "'cloud",
 "'communication",
 "'scheduling",
 "'python",
 "'reporting",
 "'css",
 "'computer",
 'science',
 "'tensorflow",
 "'engineering",
 "'mock",
 "'java",
 "'js",
 "'html",
 "'ai",
 "'physics",
 "'research",
 "'math",
 "'system",
 "'business",
 'intelligence',
 "'writing",
 "'finance",
 "'presentation",
 "'flask",
 "'security",
 "'pytorch",
 "'chemistry",
 "'analysis",
 "'conversion",
 "'teaching",
 "'github",
 "'analyze",
 "'algorithms",
 "'selenium",
 "'try",
 "'product",
 'owner',
 "'programming",
 '``',
 'none,5.0',
 'cv\\1.0.pdf',
 '``',
 'le',
 'thanh',
 'longresearch',
 'developmentphone',
 '096-997-3012',
 'date',
 'birth',
 '26/09/2001address',
 'ha',
 'noi',
 'viet',
 'name-mail',
 'attentionocr',
 'gmail.comoverviewexperience',
 'programming',
 'good',
 'communication',
 'quick',

In [96]:
key_word = get_key_word(NLP_Processed_CV)
key_word

(("'agile", "'linux"), 2)
(("'ai", "'physics"), 2)
(("'ai", 'c++'), 4)
(("'algorithms", "'email"), 2)
(("'algorithms", "'machine"), 2)
(("'algorithms", "'selenium"), 2)
(("'analysis", "'algorithms"), 2)
(("'analysis", "'certification"), 2)
(("'analyze", "'algorithms"), 2)
(("'api", "'research"), 3)
(("'architecture", "'tensorflow"), 2)
(("'architecture", "'testing"), 2)
(("'business", 'intelligence'), 2)
(("'chemistry", "'analysis"), 2)
(("'cloud", "'communication"), 5)
(("'communication", "'css"), 3)
(("'communication", "'python"), 3)
(("'communication", "'scheduling"), 2)
(("'computer", 'science'), 5)
(("'conversion", "'teaching"), 2)
(("'css", "'communication"), 2)
(("'css", "'computer"), 2)
(("'data", 'analysis'), 2)
(("'database", "'javascript"), 2)
(("'database", "'programming"), 2)
(("'design", "'ai"), 3)
(("'design", 'c++'), 4)
(("'docker", "'architecture"), 2)
(("'documentation", "'api"), 2)
(("'email", "'try"), 2)
(("'engineering", "'java"), 3)
(("'english", "'process"), 2)
(

["'agile 'linux",
 "'ai 'physics",
 "'ai c++",
 "'algorithms 'email",
 "'algorithms 'machine",
 "'algorithms 'selenium",
 "'analysis 'algorithms",
 "'analysis 'certification",
 "'analyze 'algorithms",
 "'api 'research",
 "'architecture 'tensorflow",
 "'architecture 'testing",
 "'business intelligence",
 "'chemistry 'analysis",
 "'cloud 'communication",
 "'communication 'css",
 "'communication 'python",
 "'communication 'scheduling",
 "'computer science",
 "'conversion 'teaching",
 "'css 'communication",
 "'css 'computer",
 "'data analysis",
 "'database 'javascript",
 "'database 'programming",
 "'design 'ai",
 "'design c++",
 "'docker 'architecture",
 "'documentation 'api",
 "'email 'try",
 "'engineering 'java",
 "'english 'process",
 "'flask 'security",
 "'forecasting 'design",
 "'github 'analyze",
 "'github 'mysql",
 "'html 'ai",
 "'html 'design",
 "'information technology",
 "'java 'technical",
 "'javascript 'programming",
 "'js 'html",
 "'linux 'docker",
 "'machine learning",
 "'mat

# Importing scapped df

In [97]:
import os
import pandas as pd

DF_PATH = r"C:\Users\Admin\Downloads\Job-Recomendation-main\Job-Recomendation-main\data\scrapped_data\jobs.csv"

# Kiểm tra tồn tại file
if os.path.exists(DF_PATH):
    print("✅ File tồn tại!")
    
    # Kiểm tra quyền đọc
    if os.access(DF_PATH, os.R_OK):
        print("✅ Có quyền đọc file!")
        
        # Thử đọc file
        try:
            df = pd.read_csv(DF_PATH, encoding='utf-8')  # Thử encoding khác nếu cần
            print(df.head())
        except Exception as e:
            print(f"❌ Lỗi đọc file: {str(e)}")
    else:
        print("❌ Không có quyền đọc file!")
else:
    print("❌ File không tồn tại!")

✅ File tồn tại!
✅ Có quyền đọc file!
                Job Title                                    Job Description  \
0       Software Engineer  Design cloud-based solutions using JSP and HTM...   
1  Database Administrator  Enhance web applications using Python and C# f...   
2        Network Engineer  Architect real-time data platforms using PHP a...   
3       Software Engineer  Enhance cloud-based solutions using CSS and C#...   
4  Database Administrator  Enhance mobile-first interfaces using JSP and ...   

         Required Skills                   Salary Range          Location  \
0        JSP, HTML, Java  35M VND/month - 41M VND/month             Hanoi   
1             C#, Python  39M VND/month - 45M VND/month             Hanoi   
2              PHP, Java  28M VND/month - 36M VND/month  Ho Chi Minh City   
3           C#, CSS, JSP  53M VND/month - 64M VND/month            Remote   
4  C#, HTML, Spring, JSP  56M VND/month - 70M VND/month             Hanoi   

          Company E

In [98]:
df = pd.read_csv(DF_PATH)
df

Job Title  \
0               Software Engineer   
1          Database Administrator   
2                Network Engineer   
3               Software Engineer   
4          Database Administrator   
...                           ...   
20015               AI Specialist   
20016  Quantum Computing Engineer   
20017         Java Web Specialist   
20018        AI Ethics Consultant   
20019        AI Ethics Consultant   

                                         Job Description  \
0      Design cloud-based solutions using JSP and HTM...   
1      Enhance web applications using Python and C# f...   
2      Architect real-time data platforms using PHP a...   
3      Enhance cloud-based solutions using CSS and C#...   
4      Enhance mobile-first interfaces using JSP and ...   
...                                                  ...   
20015  Maintain financial services using Python and J...   
20016  Lead AI-driven tools using Quantum Computing a...   
20017  Optimize real-time data platforms using Python...   
20018  Implement e-commerce systems using Kubernetes ...   
20019  Design cloud-based solutions using Java and Ty...   

                         Required Skills                   Salary Range  \
0                        JSP, HTML, Java  35M VND/month - 41M VND/month   
1                             C#, Python  39M VND/month - 45M VND/month   
2                              PHP, Java  28M VND/month - 36M VND/month   
3                           C#, CSS, JSP  53M VND/month - 64M VND/month   
4                  C#, HTML, Spring, JSP  56M VND/month - 70M VND/month   
...                                  ...                            ...   
20015  TypeScript, Java, Python, Jenkins  28M VND/month - 37M VND/month   
20016  Azure, Next.js, Quantum Computing  32M VND/month - 37M VND/month   
20017              Next.js, Java, Python  60M VND/month - 66M VND/month   
20018          Jenkins, Kubernetes, Java  42M VND/month - 50M VND/month   
20019      TypeScript, Spring Boot, Java  57M VND/month - 63M VND/month   

               Location         Company Experience Level  \
0                 Hanoi    FPT Software        Mid-Level   
1                 Hanoi  Shopee Vietnam        Mid-Level   
2      Ho Chi Minh City      CMC Global      Entry-Level   
3                Remote     Axon Active     Senior-Level   
4                 Hanoi           VinAI     Senior-Level   
...                 ...             ...              ...   
20015             Hanoi  KMS Technology      Entry-Level   
20016           Da Nang        NashTech        Mid-Level   
20017            Remote             VNG     Senior-Level   
20018  Ho Chi Minh City   TMA Solutions        Mid-Level   
20019           Da Nang         Haravan     Senior-Level   

                      Industry       Job Type Date Posted  \
0           Mobile Development      Part-Time   14/8/2019   
1         Software Development      Full-Time   21/6/2019   
2         Software Development      Full-Time   29/5/2019   
3                Cybersecurity      Part-Time   26/3/2019   
4              Web Development      Full-Time   26/3/2019   
...                        ...            ...         ...   
20015          Cloud Computing      Full-Time    5/1/2025   
20016          Cloud Computing  Contract-Type   13/2/2025   
20017  Artificial Intelligence      Full-Time   17/1/2025   
20018          Cloud Computing      Full-Time    9/2/2025   
20019     Software Development      Full-Time   17/1/2025   

                             externalApplyLink  \
0             https://careers.fptsoftware.com/   
1                   https://careers.shopee.vn/   
2             https://cmcglobal.com.vn/career/   
3          https://www.axonactive.com/careers/   
4                    https://vinai.io/careers/   
...                                        ...   
20015      https://kms-technology.com/careers/   
20016  https://www.nashtechglobal.com/careers/   
20017               https://career.vng.com.vn/   
200

In [99]:
df["JobID"]=df.index

In [100]:
df["Job Description	"]=df.index

In [101]:
df

Job Title  \
0               Software Engineer   
1          Database Administrator   
2                Network Engineer   
3               Software Engineer   
4          Database Administrator   
...                           ...   
20015               AI Specialist   
20016  Quantum Computing Engineer   
20017         Java Web Specialist   
20018        AI Ethics Consultant   
20019        AI Ethics Consultant   

                                         Job Description  \
0      Design cloud-based solutions using JSP and HTM...   
1      Enhance web applications using Python and C# f...   
2      Architect real-time data platforms using PHP a...   
3      Enhance cloud-based solutions using CSS and C#...   
4      Enhance mobile-first interfaces using JSP and ...   
...                                                  ...   
20015  Maintain financial services using Python and J...   
20016  Lead AI-driven tools using Quantum Computing a...   
20017  Optimize real-time data platforms using Python...   
20018  Implement e-commerce systems using Kubernetes ...   
20019  Design cloud-based solutions using Java and Ty...   

                         Required Skills                   Salary Range  \
0                        JSP, HTML, Java  35M VND/month - 41M VND/month   
1                             C#, Python  39M VND/month - 45M VND/month   
2                              PHP, Java  28M VND/month - 36M VND/month   
3                           C#, CSS, JSP  53M VND/month - 64M VND/month   
4                  C#, HTML, Spring, JSP  56M VND/month - 70M VND/month   
...                                  ...                            ...   
20015  TypeScript, Java, Python, Jenkins  28M VND/month - 37M VND/month   
20016  Azure, Next.js, Quantum Computing  32M VND/month - 37M VND/month   
20017              Next.js, Java, Python  60M VND/month - 66M VND/month   
20018          Jenkins, Kubernetes, Java  42M VND/month - 50M VND/month   
20019      TypeScript, Spring Boot, Java  57M VND/month - 63M VND/month   

               Location         Company Experience Level  \
0                 Hanoi    FPT Software        Mid-Level   
1                 Hanoi  Shopee Vietnam        Mid-Level   
2      Ho Chi Minh City      CMC Global      Entry-Level   
3                Remote     Axon Active     Senior-Level   
4                 Hanoi           VinAI     Senior-Level   
...                 ...             ...              ...   
20015             Hanoi  KMS Technology      Entry-Level   
20016           Da Nang        NashTech        Mid-Level   
20017            Remote             VNG     Senior-Level   
20018  Ho Chi Minh City   TMA Solutions        Mid-Level   
20019           Da Nang         Haravan     Senior-Level   

                      Industry       Job Type Date Posted  \
0           Mobile Development      Part-Time   14/8/2019   
1         Software Development      Full-Time   21/6/2019   
2         Software Development      Full-Time   29/5/2019   
3                Cybersecurity      Part-Time   26/3/2019   
4              Web Development      Full-Time   26/3/2019   
...                        ...            ...         ...   
20015          Cloud Computing      Full-Time    5/1/2025   
20016          Cloud Computing  Contract-Type   13/2/2025   
20017  Artificial Intelligence      Full-Time   17/1/2025   
20018          Cloud Computing      Full-Time    9/2/2025   
20019     Software Development      Full-Time   17/1/2025   

                             externalApplyLink  \
0             https://careers.fptsoftware.com/   
1                   https://careers.shopee.vn/   
2             https://cmcglobal.com.vn/career/   
3          https://www.axonactive.com/careers/   
4                    https://vinai.io/careers/   
...                                        ...   
20015      https://kms-technology.com/careers/   
20016  https://www.nashtechglobal.com/careers/   
20017               https://career.vng.com.vn/   
200

In [102]:
df.shape


(20020, 14)

In [103]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20020 entries, 0 to 20019
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Job Title          20020 non-null  object
 1   Job Description    20020 non-null  object
 2   Required Skills    20020 non-null  object
 3   Salary Range       20020 non-null  object
 4   Location           20020 non-null  object
 5   Company            20020 non-null  object
 6   Experience Level   20020 non-null  object
 7   Industry           20020 non-null  object
 8   Job Type           20020 non-null  object
 9   Date Posted        20020 non-null  object
 10  externalApplyLink  20020 non-null  object
 11  url                20020 non-null  object
 12  JobID              20020 non-null  int64 
 13  Job Description	   20020 non-null  int64 
dtypes: int64(2), object(12)
memory usage: 2.1+ MB


In [104]:
df['All'] = df[df.columns[0:]].apply(
    lambda x: ','.join(x.dropna().astype(str)),
    axis=1
)

In [105]:
df

Job Title  \
0               Software Engineer   
1          Database Administrator   
2                Network Engineer   
3               Software Engineer   
4          Database Administrator   
...                           ...   
20015               AI Specialist   
20016  Quantum Computing Engineer   
20017         Java Web Specialist   
20018        AI Ethics Consultant   
20019        AI Ethics Consultant   

                                         Job Description  \
0      Design cloud-based solutions using JSP and HTM...   
1      Enhance web applications using Python and C# f...   
2      Architect real-time data platforms using PHP a...   
3      Enhance cloud-based solutions using CSS and C#...   
4      Enhance mobile-first interfaces using JSP and ...   
...                                                  ...   
20015  Maintain financial services using Python and J...   
20016  Lead AI-driven tools using Quantum Computing a...   
20017  Optimize real-time data platforms using Python...   
20018  Implement e-commerce systems using Kubernetes ...   
20019  Design cloud-based solutions using Java and Ty...   

                         Required Skills                   Salary Range  \
0                        JSP, HTML, Java  35M VND/month - 41M VND/month   
1                             C#, Python  39M VND/month - 45M VND/month   
2                              PHP, Java  28M VND/month - 36M VND/month   
3                           C#, CSS, JSP  53M VND/month - 64M VND/month   
4                  C#, HTML, Spring, JSP  56M VND/month - 70M VND/month   
...                                  ...                            ...   
20015  TypeScript, Java, Python, Jenkins  28M VND/month - 37M VND/month   
20016  Azure, Next.js, Quantum Computing  32M VND/month - 37M VND/month   
20017              Next.js, Java, Python  60M VND/month - 66M VND/month   
20018          Jenkins, Kubernetes, Java  42M VND/month - 50M VND/month   
20019      TypeScript, Spring Boot, Java  57M VND/month - 63M VND/month   

               Location         Company Experience Level  \
0                 Hanoi    FPT Software        Mid-Level   
1                 Hanoi  Shopee Vietnam        Mid-Level   
2      Ho Chi Minh City      CMC Global      Entry-Level   
3                Remote     Axon Active     Senior-Level   
4                 Hanoi           VinAI     Senior-Level   
...                 ...             ...              ...   
20015             Hanoi  KMS Technology      Entry-Level   
20016           Da Nang        NashTech        Mid-Level   
20017            Remote             VNG     Senior-Level   
20018  Ho Chi Minh City   TMA Solutions        Mid-Level   
20019           Da Nang         Haravan     Senior-Level   

                      Industry       Job Type Date Posted  \
0           Mobile Development      Part-Time   14/8/2019   
1         Software Development      Full-Time   21/6/2019   
2         Software Development      Full-Time   29/5/2019   
3                Cybersecurity      Part-Time   26/3/2019   
4              Web Development      Full-Time   26/3/2019   
...                        ...            ...         ...   
20015          Cloud Computing      Full-Time    5/1/2025   
20016          Cloud Computing  Contract-Type   13/2/2025   
20017  Artificial Intelligence      Full-Time   17/1/2025   
20018          Cloud Computing      Full-Time    9/2/2025   
20019     Software Development      Full-Time   17/1/2025   

                             externalApplyLink  \
0             https://careers.fptsoftware.com/   
1                   https://careers.shopee.vn/   
2             https://cmcglobal.com.vn/career/   
3          https://www.axonactive.com/careers/   
4                    https://vinai.io/careers/   
...                                        ...   
20015      https://kms-technology.com/careers/   
20016  https://www.nashtechglobal.com/careers/   
20017               https://career.vng.com.vn/   
200

In [106]:
df['All']

0        Software Engineer,Design cloud-based solutions...
1        Database Administrator,Enhance web application...
2        Network Engineer,Architect real-time data plat...
3        Software Engineer,Enhance cloud-based solution...
4        Database Administrator,Enhance mobile-first in...
                               ...                        
20015    AI Specialist,Maintain financial services usin...
20016    Quantum Computing Engineer,Lead AI-driven tool...
20017    Java Web Specialist,Optimize real-time data pl...
20018    AI Ethics Consultant,Implement e-commerce syst...
20019    AI Ethics Consultant,Design cloud-based soluti...
Name: All, Length: 20020, dtype: object

In [107]:
df["Job Description"].replace(r'\n','', regex=True,inplace=True)
df["Job Description"].replace(r'\r','', regex=True,inplace=True)  
df = df.replace(' ', '')
df["Job Description"] = df["Job Description"].str.strip()
df.All = df.All.str.strip()

In [108]:
df

Job Title  \
0               Software Engineer   
1          Database Administrator   
2                Network Engineer   
3               Software Engineer   
4          Database Administrator   
...                           ...   
20015               AI Specialist   
20016  Quantum Computing Engineer   
20017         Java Web Specialist   
20018        AI Ethics Consultant   
20019        AI Ethics Consultant   

                                         Job Description  \
0      Design cloud-based solutions using JSP and HTM...   
1      Enhance web applications using Python and C# f...   
2      Architect real-time data platforms using PHP a...   
3      Enhance cloud-based solutions using CSS and C#...   
4      Enhance mobile-first interfaces using JSP and ...   
...                                                  ...   
20015  Maintain financial services using Python and J...   
20016  Lead AI-driven tools using Quantum Computing a...   
20017  Optimize real-time data platforms using Python...   
20018  Implement e-commerce systems using Kubernetes ...   
20019  Design cloud-based solutions using Java and Ty...   

                         Required Skills                   Salary Range  \
0                        JSP, HTML, Java  35M VND/month - 41M VND/month   
1                             C#, Python  39M VND/month - 45M VND/month   
2                              PHP, Java  28M VND/month - 36M VND/month   
3                           C#, CSS, JSP  53M VND/month - 64M VND/month   
4                  C#, HTML, Spring, JSP  56M VND/month - 70M VND/month   
...                                  ...                            ...   
20015  TypeScript, Java, Python, Jenkins  28M VND/month - 37M VND/month   
20016  Azure, Next.js, Quantum Computing  32M VND/month - 37M VND/month   
20017              Next.js, Java, Python  60M VND/month - 66M VND/month   
20018          Jenkins, Kubernetes, Java  42M VND/month - 50M VND/month   
20019      TypeScript, Spring Boot, Java  57M VND/month - 63M VND/month   

               Location         Company Experience Level  \
0                 Hanoi    FPT Software        Mid-Level   
1                 Hanoi  Shopee Vietnam        Mid-Level   
2      Ho Chi Minh City      CMC Global      Entry-Level   
3                Remote     Axon Active     Senior-Level   
4                 Hanoi           VinAI     Senior-Level   
...                 ...             ...              ...   
20015             Hanoi  KMS Technology      Entry-Level   
20016           Da Nang        NashTech        Mid-Level   
20017            Remote             VNG     Senior-Level   
20018  Ho Chi Minh City   TMA Solutions        Mid-Level   
20019           Da Nang         Haravan     Senior-Level   

                      Industry       Job Type Date Posted  \
0           Mobile Development      Part-Time   14/8/2019   
1         Software Development      Full-Time   21/6/2019   
2         Software Development      Full-Time   29/5/2019   
3                Cybersecurity      Part-Time   26/3/2019   
4              Web Development      Full-Time   26/3/2019   
...                        ...            ...         ...   
20015          Cloud Computing      Full-Time    5/1/2025   
20016          Cloud Computing  Contract-Type   13/2/2025   
20017  Artificial Intelligence      Full-Time   17/1/2025   
20018          Cloud Computing      Full-Time    9/2/2025   
20019     Software Development      Full-Time   17/1/2025   

                             externalApplyLink  \
0             https://careers.fptsoftware.com/   
1                   https://careers.shopee.vn/   
2             https://cmcglobal.com.vn/career/   
3          https://www.axonactive.com/careers/   
4                    https://vinai.io/careers/   
...                                        ...   
20015      https://kms-technology.com/careers/   
20016  https://www.nashtechglobal.com/careers/   
20017               https://career.vng.com.vn/   
200

In [109]:
df.to_csv("final_job.csv",index=False)


# Put keywords of the CV into a dataframe

In [110]:
df2 = pd.DataFrame()
# append columns to an empty DataFrame
df2['title'] = ["I"]
df2['job highlights'] = ["I"]
df2['job description'] = ["I"]
df2['company overview'] = ["I"]
df2['industry'] = ["I"]

# Compare with the key words from CV only
df2['All'] = " ".join(key_word)

In [111]:
df2

title job highlights job description company overview industry  \
0     I              I               I                I        I   

                                                 All  
0  'agile 'linux 'ai 'physics 'ai c++ 'algorithms...

In [112]:
df.columns

Index(['Job Title', 'Job Description', 'Required Skills', 'Salary Range',
       'Location', 'Company', 'Experience Level', 'Industry', 'Job Type',
       'Date Posted', 'externalApplyLink', 'url', 'JobID', 'Job Description\t',
       'All'],
      dtype='object')

# Recomendation Function

#klnsdsd

In [113]:
def get_recommendation(top, df_all, scores):
    recommendation = pd.DataFrame(columns = ['Job Title', 'Company',"Location",'JobID','Job Description','score'])
    count = 0
    for i in top:
#         recommendation.at[count, 'ApplicantID'] = u
        
        recommendation.at[count, 'Job Title'] = df['Job Title'][i]
        recommendation.at[count, 'Company'] = df['Company'][i]
        recommendation.at[count, 'Location'] = df['Location'][i]
        recommendation.at[count, 'JobID'] = df.index[i]
        recommendation.at[count, 'Job Description'] = df['Job Description'][i]
        recommendation.at[count, 'score'] =  scores[count]
        count += 1
    return recommendation

## cosine_similarity + TfidfVectorizer function

In [114]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer


def TFIDF(scraped_data, cv):
    tfidf_vectorizer = TfidfVectorizer(stop_words='english')

    # TF-IDF Scraped data
    tfidf_jobid = tfidf_vectorizer.fit_transform(scraped_data)

    # TF-IDF CV
    user_tfidf = tfidf_vectorizer.transform(cv)

    # Using cosine_similarity on (Scraped data) & (CV)
    cos_similarity_tfidf = map(lambda x: cosine_similarity(user_tfidf,x),tfidf_jobid)

    output2 = list(cos_similarity_tfidf)
    return output2
    
output2 = TFIDF(df['All'], df2['All'])


In [115]:
len(output2)

20020

In [116]:
output2


[array([[0.18360148]]),
 array([[0.15304055]]),
 array([[0.11121275]]),
 array([[0.1306144]]),
 array([[0.1093997]]),
 array([[0.1479748]]),
 array([[0.16964251]]),
 array([[0.14250679]]),
 array([[0.15576919]]),
 array([[0.20155286]]),
 array([[0.14555204]]),
 array([[0.19861919]]),
 array([[0.12567653]]),
 array([[0.25058012]]),
 array([[0.07780204]]),
 array([[0.1444161]]),
 array([[0.14445238]]),
 array([[0.19355942]]),
 array([[0.03968006]]),
 array([[0.11274924]]),
 array([[0.14953804]]),
 array([[0.08765186]]),
 array([[0.13322717]]),
 array([[0.16696958]]),
 array([[0.12950881]]),
 array([[0.1448688]]),
 array([[0.15691594]]),
 array([[0.10394268]]),
 array([[0.22202909]]),
 array([[0.15802442]]),
 array([[0.12884234]]),
 array([[0.18051633]]),
 array([[0.12852304]]),
 array([[0.13893579]]),
 array([[0.04313965]]),
 array([[0.05229781]]),
 array([[0.0843174]]),
 array([[0.04945039]]),
 array([[0.06848641]]),
 array([[0.03782628]]),
 array([[0.09902882]]),
 array([[0.09273238]])

In [117]:
top = sorted(range(len(output2)), key=lambda i: output2[i], reverse=True)[:100]
list_scores = [output2[i][0][0] for i in top]
TF=get_recommendation(top,df, list_scores)
TF

Job Title         Company          Location  JobID  \
0            Web App Engineer  KMS Technology  Ho Chi Minh City   6955   
1    Cybersecurity Specialist  KMS Technology            Remote  19809   
2              Java Developer  KMS Technology           Da Nang   1249   
3   Machine Learning Engineer  KMS Technology             Hanoi  10352   
4               API Developer  KMS Technology            Remote   9688   
..                        ...             ...               ...    ...   
95     Database Administrator  KMS Technology  Ho Chi Minh City    723   
96            DevOps Engineer     Axon Active            Remote   6361   
97          Backend Developer  KMS Technology            Remote   3269   
98  Web Application Developer    FPT Software           Da Nang   3505   
99  Web Application Developer  KMS Technology             Hanoi   2863   

                                      Job Description     score  
0   Design real-time data platforms using Golang a...  0.322343  
1   Design microservices architecture using PyTorc...  0.321134  
2   Maintain microservices architecture using MySQ...  0.310826  
3   Integrate cloud-based solutions using SQL and ...  0.310736  
4   Build real-time data platforms using Flutter a...  0.293541  
..                                                ...       ...  
95  Architect microservices architecture using Jav...  0.230547  
96  Design real-time data platforms using Java and...  0.230539  
97  Implement enterprise software using PostgreSQL...  0.230405  
98  Lead cloud-based solutions using MongoDB and S...  0.230143  
99  Implement AI-driven tools using AWS and Python...  0.230125  

[100 rows x 6 columns]

## cosine_similarity + CountVectorizer

In [118]:

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

count_vectorizer = CountVectorizer()
count_jobid = count_vectorizer.fit_transform(df['All']) #converting job data into vectors using count vectorizers
count_jobid

<20020x27041 sparse matrix of type '<class 'numpy.int64'>'
	with 917422 stored elements in Compressed Sparse Row format>

In [119]:
# print(count_jobid)


In [120]:
user_count = count_vectorizer.transform(df2['All'])#converting user cv data into vectors using count vectorizers
user_count

<1x27041 sparse matrix of type '<class 'numpy.int64'>'
	with 83 stored elements in Compressed Sparse Row format>

In [121]:
print(user_count)


  (0, 0)	1
  (0, 11917)	1
  (0, 11919)	1
  (0, 11920)	9
  (0, 11923)	11
  (0, 11924)	12
  (0, 11926)	8
  (0, 13755)	2
  (0, 26764)	2
  (0, 26823)	12
  (0, 26826)	2
  (0, 26827)	5
  (0, 26830)	7
  (0, 26833)	3
  (0, 26834)	1
  (0, 26842)	2
  (0, 26844)	10
  (0, 26849)	2
  (0, 26851)	1
  (0, 26852)	4
  (0, 26855)	6
  (0, 26861)	5
  (0, 26863)	2
  (0, 26864)	17
  (0, 26865)	4
  :	:
  (0, 26970)	1
  (0, 26973)	2
  (0, 26974)	6
  (0, 26976)	9
  (0, 26977)	5
  (0, 26981)	3
  (0, 26982)	5
  (0, 26985)	2
  (0, 26988)	11
  (0, 26990)	4
  (0, 26996)	5
  (0, 27000)	2
  (0, 27001)	2
  (0, 27002)	1
  (0, 27004)	2
  (0, 27005)	21
  (0, 27010)	13
  (0, 27014)	14
  (0, 27017)	2
  (0, 27023)	4
  (0, 27025)	13
  (0, 27026)	5
  (0, 27028)	1
  (0, 27032)	3
  (0, 27037)	5


In [122]:
cos_similarity_countv = map(lambda x: cosine_similarity(user_count, x),count_jobid)
output3 = list(cos_similarity_countv)
#output3

In [123]:
output3

[array([[0.23245924]]),
 array([[0.23920637]]),
 array([[0.22189084]]),
 array([[0.16447555]]),
 array([[0.12057557]]),
 array([[0.17316407]]),
 array([[0.27882534]]),
 array([[0.20268423]]),
 array([[0.16695366]]),
 array([[0.27882534]]),
 array([[0.16491928]]),
 array([[0.23812676]]),
 array([[0.17181438]]),
 array([[0.26083053]]),
 array([[0.15612934]]),
 array([[0.20691624]]),
 array([[0.19011487]]),
 array([[0.25680569]]),
 array([[0.12412314]]),
 array([[0.18220305]]),
 array([[0.19672147]]),
 array([[0.19348607]]),
 array([[0.16245529]]),
 array([[0.19973776]]),
 array([[0.19255952]]),
 array([[0.18753027]]),
 array([[0.16910079]]),
 array([[0.18532973]]),
 array([[0.22491911]]),
 array([[0.26649969]]),
 array([[0.18063422]]),
 array([[0.23264796]]),
 array([[0.24211873]]),
 array([[0.23715948]]),
 array([[0.13114765]]),
 array([[0.12610861]]),
 array([[0.26195034]]),
 array([[0.10867083]]),
 array([[0.12235947]]),
 array([[0.11160841]]),
 array([[0.17539853]]),
 array([[0.17444

In [124]:
top = sorted(range(len(output3)), key=lambda i: output3[i], reverse=True)[:100]
list_scores = [output3[i][0][0] for i in top]
cv=get_recommendation(top, df, list_scores)
cv

Job Title         Company          Location  JobID  \
0               API Developer  KMS Technology            Remote   9688   
1            Web App Engineer  KMS Technology  Ho Chi Minh City   6955   
2              Data Scientist  KMS Technology         Nha Trang   7372   
3   Machine Learning Engineer             VNG             Hanoi   8912   
4   Machine Learning Engineer  KMS Technology             Hanoi  10352   
..                        ...             ...               ...    ...   
95  Machine Learning Engineer      CMC Global  Ho Chi Minh City   9389   
96          Backend Developer  KMS Technology            Remote   3269   
97                AI Engineer  KMS Technology            Remote  16416   
98  Java Full Stack Developer      CMC Global           Da Nang  12082   
99         Java Web Developer        NashTech            Remote   7941   

                                      Job Description     score  
0   Build real-time data platforms using Flutter a...  0.402979  
1   Design real-time data platforms using Golang a...  0.402574  
2   Optimize real-time data platforms using Vue.js...  0.397933  
3   Integrate real-time data platforms using Pytho...  0.394854  
4   Integrate cloud-based solutions using SQL and ...  0.382228  
..                                                ...       ...  
95  Optimize e-commerce systems using Django and J...  0.324474  
96  Implement enterprise software using PostgreSQL...  0.324415  
97  Build real-time data platforms using Golang an...  0.323088  
98  Enhance real-time data platforms using Azure a...  0.322927  
99  Develop real-time data platforms using Golang ...  0.322914  

[100 rows x 6 columns]

In [125]:
# Truy cập phần tử thứ 1 trong cột "Job Description"
job_desc = cv["Job Description"][1]
print(job_desc)

Design real-time data platforms using Golang and Python for KMS Technology's machine learning models to enhance user experience.


## TfidfVectorizer + NearestNeighbors

In [126]:
from sklearn.neighbors import NearestNeighbors

def KNN(scraped_data, cv):
    tfidf_vectorizer = TfidfVectorizer(stop_words='english')

    
    KNN = NearestNeighbors(n_neighbors=100, metric='cosine')  # Sử dụng cosine similarity
    KNN.fit(tfidf_vectorizer.fit_transform(scraped_data))
#     NNs = KNN.kneighbors(tfidf_vectorizer.transform(cv), return_distance=True)
    NNs = KNN.kneighbors(tfidf_vectorizer.transform(cv))
    top = NNs[1][0][1:]
    index_score = NNs[0][0][1:]

    knn = get_recommendation(top, df, index_score)
    return knn

knn = KNN(df['All'], df2['All'])
knn

Job Title         Company          Location  JobID  \
0    Cybersecurity Specialist  KMS Technology            Remote  19809   
1              Java Developer  KMS Technology           Da Nang   1249   
2   Machine Learning Engineer  KMS Technology             Hanoi  10352   
3               API Developer  KMS Technology            Remote   9688   
4   Machine Learning Engineer  KMS Technology  Ho Chi Minh City  11084   
..                        ...             ...               ...    ...   
94     Database Administrator  KMS Technology  Ho Chi Minh City    723   
95            DevOps Engineer     Axon Active            Remote   6361   
96          Backend Developer  KMS Technology            Remote   3269   
97  Web Application Developer    FPT Software           Da Nang   3505   
98  Web Application Developer  KMS Technology             Hanoi   2863   

                                      Job Description     score  
0   Design microservices architecture using PyTorc...  0.678866  
1   Maintain microservices architecture using MySQ...  0.689174  
2   Integrate cloud-based solutions using SQL and ...  0.689264  
3   Build real-time data platforms using Flutter a...  0.706459  
4   Integrate microservices architecture using Rea...  0.716252  
..                                                ...       ...  
94  Architect microservices architecture using Jav...  0.769453  
95  Design real-time data platforms using Java and...  0.769461  
96  Implement enterprise software using PostgreSQL...  0.769595  
97  Lead cloud-based solutions using MongoDB and S...  0.769857  
98  Implement AI-driven tools using AWS and Python...  0.769875  

[99 rows x 6 columns]

In [127]:

knn.to_csv('knn.csv', index=False)

In [128]:
cv

Job Title         Company          Location  JobID  \
0               API Developer  KMS Technology            Remote   9688   
1            Web App Engineer  KMS Technology  Ho Chi Minh City   6955   
2              Data Scientist  KMS Technology         Nha Trang   7372   
3   Machine Learning Engineer             VNG             Hanoi   8912   
4   Machine Learning Engineer  KMS Technology             Hanoi  10352   
..                        ...             ...               ...    ...   
95  Machine Learning Engineer      CMC Global  Ho Chi Minh City   9389   
96          Backend Developer  KMS Technology            Remote   3269   
97                AI Engineer  KMS Technology            Remote  16416   
98  Java Full Stack Developer      CMC Global           Da Nang  12082   
99         Java Web Developer        NashTech            Remote   7941   

                                      Job Description     score  
0   Build real-time data platforms using Flutter a...  0.402979  
1   Design real-time data platforms using Golang a...  0.402574  
2   Optimize real-time data platforms using Vue.js...  0.397933  
3   Integrate real-time data platforms using Pytho...  0.394854  
4   Integrate cloud-based solutions using SQL and ...  0.382228  
..                                                ...       ...  
95  Optimize e-commerce systems using Django and J...  0.324474  
96  Implement enterprise software using PostgreSQL...  0.324415  
97  Build real-time data platforms using Golang an...  0.323088  
98  Enhance real-time data platforms using Azure a...  0.322927  
99  Develop real-time data platforms using Golang ...  0.322914  

[100 rows x 6 columns]

## Combined TFIDF, CV and KNN result together, to make a dataframe "final"


In [129]:
merge1 = knn[['JobID','Job Title', 'score']].merge(TF[['JobID','score']], on= "JobID")

In [130]:
# merge1 = knn[['JobID','title', 'score']].merge(TF[['JobID','score']], on= "JobID")
# final = merge1.merge(cv[['JobID','score']], on = "JobID")
# final = final.rename(columns={"score_x": "KNN", "score_y": "TF-IDF","score": "CV"})
# final.head()a

final = merge1.merge(cv[['JobID','score']], on = "JobID")
final = final.rename(columns={"score_x": "KNN", "score_y": "TF-IDF","score": "CV"})
final.head()

JobID                  Job Title       KNN    TF-IDF        CV
0  19809   Cybersecurity Specialist  0.678866  0.321134  0.345798
1   1249             Java Developer  0.689174  0.310826  0.357363
2  10352  Machine Learning Engineer  0.689264  0.310736  0.382228
3   9688              API Developer  0.706459  0.293541  0.402979
4  11084  Machine Learning Engineer  0.716252  0.283748  0.347751

In [131]:
final

JobID                   Job Title       KNN    TF-IDF        CV
0   19809    Cybersecurity Specialist  0.678866  0.321134  0.345798
1    1249              Java Developer  0.689174  0.310826  0.357363
2   10352   Machine Learning Engineer  0.689264  0.310736  0.382228
3    9688               API Developer  0.706459  0.293541  0.402979
4   11084   Machine Learning Engineer  0.716252  0.283748  0.347751
5    8912   Machine Learning Engineer  0.716893  0.283107  0.394854
6    8829   Machine Learning Engineer  0.719801  0.280199  0.335055
7     535        System Administrator  0.720748  0.279252  0.376741
8   16179                 AI Engineer  0.728089  0.271911  0.360272
9   11504  Web Application Specialist  0.732991  0.267009  0.328313
10   8373        Full Stack Developer  0.736681  0.263319  0.325951
11  11410   Machine Learning Engineer  0.737466  0.262534  0.326995
12   9635      Java Backend Developer  0.738789  0.261211  0.369029
13   8705               API Developer   0.74175   0.25825  0.348689
14   7372              Data Scientist  0.742191  0.257809  0.397933
15   7633                 AI Engineer  0.743729  0.256271  0.330252
16    906              Java Developer  0.743797  0.256203  0.327835
17  12426                 AI Engineer   0.74575   0.25425  0.342857
18    932        System Administrator  0.748424  0.251576  0.326271
19  11641       Cybersecurity Analyst  0.748982  0.251018  0.345798
20  10656              Data Scientist  0.749063  0.250937  0.338075
21  10016              Data Scientist  0.750218  0.249782  0.357621
22   7442                 AI Engineer  0.750726  0.249274  0.349323
23   9792   Machine Learning Engineer   0.75158   0.24842  0.339588
24  10250               API Developer  0.752289  0.247711  0.339782
25   8958   Machine Learning Engineer  0.755299  0.244701  0.347731
26  11007      Java Backend Developer  0.755851  0.244149  0.358564
27  10387               API Developer  0.755981  0.244019  0.324718
28  12045  Web Application Specialist    0.7573    0.2427  0.359097
29   8695             DevOps Engineer  0.758491  0.241509   0.35798
30   5807            Web App Engineer  0.759159  0.240841  0.327905
31  19903               AI Specialist  0.759971  0.240029   0.33847
32  10787   Machine Learning Engineer  0.760043  0.239957  0.360512
33  15181              Java Developer  0.762162  0.237838  0.341139
34   8187            Web App Engineer   0.76415   0.23585  0.377675
35   6322              Data Scientist  0.764178  0.235822  0.330185
36   4689              Data Scientist  0.764296  0.235704   0.32783
37  15989     Full Stack Web Engineer  0.764426  0.235574   0.33981
38  13272                 AI Engineer  0.764439  0.235561  0.347814
39   8137        Full Stack Developer  0.764484  0.235516  0.344747
40  14035        Senior Web Developer  0.765726  0.234274  0.343164
41   1108        System Administrator  0.766439  0.233561    0.3254
42  16108              Java Developer  0.768068  0.231932  0.326695
43  13268                 AI Engineer  0.768608  0.231392  0.332918
44  10885             DevOps Engineer  0.769139  0.230861  0.340345
45   6361             DevOps Engineer  0.769461  0.230539  0.352291
46   3269           Backend Developer  0.769595  0.230405  0.324415

In [132]:
# Scale it
from sklearn.preprocessing import MinMaxScaler
slr = MinMaxScaler()
final[["KNN", "TF-IDF", 'CV']] = slr.fit_transform(final[["KNN", "TF-IDF", 'CV']])

# Multiply by weights
final['KNN'] = (1-final['KNN'])/3
final['TF-IDF'] = final['TF-IDF']/3
final['CV'] = final['CV']/3
final['Final'] = final['KNN']+final['TF-IDF']+final['CV']
final.sort_values(by="Final", ascending=False)

JobID                   Job Title       KNN    TF-IDF        CV     Final
2   10352   Machine Learning Engineer  0.295135  0.295135  0.245291  0.835561
3    9688               API Developer  0.231960  0.231960  0.333333  0.797254
0   19809    Cybersecurity Specialist  0.333333  0.333333  0.090725  0.757392
1    1249              Java Developer  0.295464  0.295464  0.139791  0.730718
5    8912   Machine Learning Engineer  0.193625  0.193625  0.298862  0.686111
7     535        System Administrator  0.179464  0.179464  0.222012  0.580939
14   7372              Data Scientist  0.100680  0.100680  0.311923  0.513283
4   11084   Machine Learning Engineer  0.195981  0.195981  0.099010  0.490972
8   16179                 AI Engineer  0.152492  0.152492  0.152134  0.457118
12   9635      Java Backend Developer  0.113180  0.113180  0.189288  0.415649
6    8829   Machine Learning Engineer  0.182940  0.182940  0.045141  0.411022
13   8705               API Developer  0.102303  0.102303  0.102989  0.307595
9   11504  Web Application Specialist  0.134483  0.134483  0.016536  0.285501
21  10016              Data Scientist  0.071190  0.071190  0.140888  0.283268
34   8187            Web App Engineer  0.020006  0.020006  0.225973  0.265986
17  12426                 AI Engineer  0.087605  0.087605  0.078245  0.253455
10   8373        Full Stack Developer  0.120927  0.120927  0.006517  0.248370
11  11410   Machine Learning Engineer  0.118041  0.118041  0.010945  0.247027
26  11007      Java Backend Developer  0.050496  0.050496  0.144889  0.245881
22   7442                 AI Engineer  0.069325  0.069325  0.105678  0.244328
19  11641       Cybersecurity Analyst  0.075732  0.075732  0.090725  0.242190
28  12045  Web Application Specialist  0.045170  0.045170  0.147151  0.237492
29   8695             DevOps Engineer  0.040795  0.040795  0.142408  0.223999
32  10787   Machine Learning Engineer  0.035093  0.035093  0.153153  0.223339
15   7633                 AI Engineer  0.095030  0.095030  0.024764  0.214824
20  10656              Data Scientist  0.075435  0.075435  0.057956  0.208826
16    906              Java Developer  0.094783  0.094783  0.014508  0.204073
25   8958   Machine Learning Engineer  0.052524  0.052524  0.098925  0.203973
23   9792   Machine Learning Engineer  0.066189  0.066189  0.064375  0.196752
24  10250               API Developer  0.063581  0.063581  0.065200  0.192361
18    932        System Administrator  0.077780  0.077780  0.007874  0.163435
38  13272                 AI Engineer  0.018945  0.018945  0.099278  0.137167
31  19903               AI Specialist  0.035360  0.035360  0.059631  0.130351
33  15181              Java Developer  0.027309  0.027309  0.070957  0.125575
39   8137        Full Stack Developer  0.018778  0.018778  0.086264  0.123821
45   6361             DevOps Engineer  0.000492  0.000492  0.118271  0.119255
40  14035        Senior Web Developer  0.014217  0.014217  0.079547  0.107981
37  15989     Full Stack Web Engineer  0.018991  0.018991  0.065316  0.103297
27  10387               API Developer  0.050018  0.050018  0.001285  0.101320
30   5807            Web App Engineer  0.038341  0.038341  0.014804  0.091485
44  10885             DevOps Engineer  0.001675  0.001675  0.067588  0.070938
35   6322              Data Scientist  0.019903  0.019903  0.024480  0.064287
36   4689              Data Scientist  0.019471  0.019471  0.014489  0.053430
43  13268                 AI Engineer  0.003627  0.003627  0.036073  0.043327
41   1108        System Administrator  0.011597  0.011597  0.004177  0.027371
42  16108              Java Developer  0.005612  0.005612  0.009674  0.020898
46   3269           Backend Developer  0.000000  0.000000  0.000000  0.000000

In [133]:
# final.to_csv('final.csv', index=False)
final2 = final.sort_values(by="Final", ascending=False).copy()
final2

JobID                   Job Title       KNN    TF-IDF        CV     Final
2   10352   Machine Learning Engineer  0.295135  0.295135  0.245291  0.835561
3    9688               API Developer  0.231960  0.231960  0.333333  0.797254
0   19809    Cybersecurity Specialist  0.333333  0.333333  0.090725  0.757392
1    1249              Java Developer  0.295464  0.295464  0.139791  0.730718
5    8912   Machine Learning Engineer  0.193625  0.193625  0.298862  0.686111
7     535        System Administrator  0.179464  0.179464  0.222012  0.580939
14   7372              Data Scientist  0.100680  0.100680  0.311923  0.513283
4   11084   Machine Learning Engineer  0.195981  0.195981  0.099010  0.490972
8   16179                 AI Engineer  0.152492  0.152492  0.152134  0.457118
12   9635      Java Backend Developer  0.113180  0.113180  0.189288  0.415649
6    8829   Machine Learning Engineer  0.182940  0.182940  0.045141  0.411022
13   8705               API Developer  0.102303  0.102303  0.102989  0.307595
9   11504  Web Application Specialist  0.134483  0.134483  0.016536  0.285501
21  10016              Data Scientist  0.071190  0.071190  0.140888  0.283268
34   8187            Web App Engineer  0.020006  0.020006  0.225973  0.265986
17  12426                 AI Engineer  0.087605  0.087605  0.078245  0.253455
10   8373        Full Stack Developer  0.120927  0.120927  0.006517  0.248370
11  11410   Machine Learning Engineer  0.118041  0.118041  0.010945  0.247027
26  11007      Java Backend Developer  0.050496  0.050496  0.144889  0.245881
22   7442                 AI Engineer  0.069325  0.069325  0.105678  0.244328
19  11641       Cybersecurity Analyst  0.075732  0.075732  0.090725  0.242190
28  12045  Web Application Specialist  0.045170  0.045170  0.147151  0.237492
29   8695             DevOps Engineer  0.040795  0.040795  0.142408  0.223999
32  10787   Machine Learning Engineer  0.035093  0.035093  0.153153  0.223339
15   7633                 AI Engineer  0.095030  0.095030  0.024764  0.214824
20  10656              Data Scientist  0.075435  0.075435  0.057956  0.208826
16    906              Java Developer  0.094783  0.094783  0.014508  0.204073
25   8958   Machine Learning Engineer  0.052524  0.052524  0.098925  0.203973
23   9792   Machine Learning Engineer  0.066189  0.066189  0.064375  0.196752
24  10250               API Developer  0.063581  0.063581  0.065200  0.192361
18    932        System Administrator  0.077780  0.077780  0.007874  0.163435
38  13272                 AI Engineer  0.018945  0.018945  0.099278  0.137167
31  19903               AI Specialist  0.035360  0.035360  0.059631  0.130351
33  15181              Java Developer  0.027309  0.027309  0.070957  0.125575
39   8137        Full Stack Developer  0.018778  0.018778  0.086264  0.123821
45   6361             DevOps Engineer  0.000492  0.000492  0.118271  0.119255
40  14035        Senior Web Developer  0.014217  0.014217  0.079547  0.107981
37  15989     Full Stack Web Engineer  0.018991  0.018991  0.065316  0.103297
27  10387               API Developer  0.050018  0.050018  0.001285  0.101320
30   5807            Web App Engineer  0.038341  0.038341  0.014804  0.091485
44  10885             DevOps Engineer  0.001675  0.001675  0.067588  0.070938
35   6322              Data Scientist  0.019903  0.019903  0.024480  0.064287
36   4689              Data Scientist  0.019471  0.019471  0.014489  0.053430
43  13268                 AI Engineer  0.003627  0.003627  0.036073  0.043327
41   1108        System Administrator  0.011597  0.011597  0.004177  0.027371
42  16108              Java Developer  0.005612  0.005612  0.009674  0.020898
46   3269           Backend Developer  0.000000  0.000000  0.000000  0.000000

In [134]:
# final2.merge(df, on="JobID")
final_df = df.merge(final2, on="JobID")
final_df

Job Title_x  \
0         System Administrator   
1               Java Developer   
2         System Administrator   
3         System Administrator   
4               Java Developer   
5            Backend Developer   
6               Data Scientist   
7             Web App Engineer   
8               Data Scientist   
9              DevOps Engineer   
10              Data Scientist   
11                 AI Engineer   
12                 AI Engineer   
13        Full Stack Developer   
14            Web App Engineer   
15        Full Stack Developer   
16             DevOps Engineer   
17               API Developer   
18   Machine Learning Engineer   
19   Machine Learning Engineer   
20   Machine Learning Engineer   
21      Java Backend Developer   
22               API Developer   
23   Machine Learning Engineer   
24              Data Scientist   
25               API Developer   
26   Machine Learning Engineer   
27               API Developer   
28              Data Scientist   
29   Machine Learning Engineer   
30             DevOps Engineer   
31      Java Backend Developer   
32   Machine Learning Engineer   
33   Machine Learning Engineer   
34  Web Application Specialist   
35       Cybersecurity Analyst   
36  Web Application Specialist   
37                 AI Engineer   
38                 AI Engineer   
39                 AI Engineer   
40        Senior Web Developer   
41              Java Developer   
42     Full Stack Web Engineer   
43              Java Developer   
44                 AI Engineer   
45    Cybersecurity Specialist   
46               AI Specialist   

                                      Job Description  \
0   Optimize enterprise software using Java and HT...   
1   Design financial services using CSS and HTML f...   
2   Enhance AI-driven tools using MySQL and HTML f...   
3   Design backend systems using JSP and MySQL for...   
4   Maintain microservices architecture using MySQ...   
5   Implement enterprise software using PostgreSQL...   
6   Design cloud-based solutions using Spring Boot...   
7   Develop web applications using Python and Spri...   
8   Lead cloud-based solutions using Angular and S...   
9   Design real-time data platforms using Java and...   
10  Optimize real-time data platforms using Vue.js...   
11  Lead real-time data platforms using Docker and...   
12  Optimize microservices architecture using Pyth...   
13  Optimize real-time data platforms using Java a...   
14  Lead real-time data platforms using Java and A...   
15  Architect real-time data platforms using Vue.j...   
16  Design real-time data platforms using Flutter ...   
17  Optimize mobile-first interfaces using Python ...   
18  Implement cloud-based solutions using AWS and ...   
19  Integrate real-time data platforms using Pytho...   
20  Enhance real-time data platforms using Java an...   
21  Integrate AI-driven tools using Java and Pytho...   
22  Build real-time data platforms using Flutter a...   
23  Enhance real-time data platforms using Spring ...   
24  Optimize e-commerce systems using React and Ja...   
25  Optimize web applications using Flutter and Py...   
26  Integrate cloud-based solutions using SQL and ...   
27  Build financial services using Flutter and Spr...   
28  Design e-commerce systems using Python and Kub...   
29  Optimize real-time data platforms using Kubern...   
30  Enhance real-time data platforms using Spring ...   
31  Lead enterprise software using Node.js and Pyt...   
32  Integrate microservices architecture using Rea...   
33  Develop microservices architecture using Djang...   
34  Design e-commerce systems using Kubernetes and...   
35  Maintain web applications using Solidity and P...   
36  Enhance real-time data platforms using Kuberne...   
37  Architect cloud-based solutions using AWS and ...   
38  Develop financial services using Java and Azur...   
39  Design real-time data platforms using GraphQL ...   
40  Lead AI-driven tools using Java and React for

In [135]:
final_df.to_csv("final_df.csv",index=False)
